name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 for Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Create application.properties
      run: |
        mkdir -p src/main/resources
        echo "DISCORD_TOKEN=${{ secrets.BOT_TOKEN }}" > src/main/resources/application.properties
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> src/main/resources/application.properties
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> src/main/resources/application.properties
    - name: Build with Maven
      run: mvn -B package --file pom.xml
